name: HukukAsistan APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Projeyi al
        uses: actions/checkout@v4

      - name: Yeni surumu ac
              run: unzip -o HukukAsistan_AI_v0.5_logolu.zip
Huk
      - name: Flutter kur
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Android dosyalarini olustur
        working-directory: HukukAsistan_AI_v0.2
        run: flutter create --platforms=android --org com.example .

      - name: Firebase ayarlarini ekle
        run: |
          cp google-services.json HukukAsistan_AI_v0.2/android/app/google-services.json
          sed -i '/id("com.android.application") version/a\    id("com.google.gms.google-services") version "4.4.4" apply false' HukukAsistan_AI_v0.2/android/settings.gradle.kts
          sed -i '/id("com.android.application")/a\    id("com.google.gms.google-services")' HukukAsistan_AI_v0.2/android/app/build.gradle.kts

      - name: Paketleri yukle
        working-directory: HukukAsistan_AI_v0.2
        run: flutter pub get
      - name: Uygulama logosunu olustur
        working-directory: HukukAsistan_AI_v0.2
        run: dart run flutter_launcher_icons
      - name: APK olustur
        working-directory: HukukAsistan_AI_v0.2
        run: flutter build apk --release

      - name: APK dosyasini kaydet
        uses: actions/upload-artifact@v4
        with:
          name: HukukAsistan-AI-v0.5-Logolu-APK 
          path: HukukAsistan_AI_v0.2/build/app/outputs/flutter-apk/app-release.apk
