name: HukukAsistan APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Projeyi al
        uses: actions/checkout@v4

      - name: ZIP dosyasini ac
        run: unzip -o HukukAsistan_AI_v0.2_github_actions.zip

      - name: Flutter kur
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Android dosyalarini olustur
        working-directory: HukukAsistan_AI_v0.2
        run: flutter create --platforms=android .

      - name: Paketleri yukle
        working-directory: HukukAsistan_AI_v0.2
        run: flutter pub get

      - name: APK olustur
        working-directory: HukukAsistan_AI_v0.2
        run: flutter build apk --release

      - name: APK dosyasini kaydet
        uses: actions/upload-artifact@v4
        with:
          name: HukukAsistan-AI-APK
          path: HukukAsistan_AI_v0.2/build/app/outputs/flutter-apk/app-release.apk
